services:
  db:
    env_file: ./backend/.env
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    env_file: ./backend/.env
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/fantasy_advisor
      CORS_ORIGINS: '["http://localhost:5173"]'
    
    develop:                                                                                                                                                                                                                                                                              
      watch:        
        - action: sync
          path: ./backend/app                                                                                                                                                                                                                                                             
          target: /backend/app
        - action: sync
          path: ./backend/tests
          target: /backend/tests
        - action: sync
          path: ./backend/alembic
          target: /backend/alembic
        - action: rebuild                                                                                                                                                                                                                          
          path: ./backend/pyproject.toml
        - action: rebuild                                                                                                                                                                                                                                                                 
          path: ./backend/uv.lock

  
volumes:
  db_data:
