"""add core models

Revision ID: f84adc8eb5f3
Revises:
Create Date: 2026-04-20 17:05:58.301919

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f84adc8eb5f3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("sleeper_id", sa.String(), nullable=True),
        sa.Column("fantasycalc_id", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("position", sa.String(), nullable=False),
        sa.Column("nfl_team", sa.String(), nullable=True),
        sa.Column("age", sa.Float(), nullable=True),
        sa.Column("years_exp", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_players_fantasycalc_id"), "players", ["fantasycalc_id"], unique=True)
    op.create_index(op.f("ix_players_full_name"), "players", ["full_name"], unique=False)
    op.create_index(op.f("ix_players_id"), "players", ["id"], unique=True)
    op.create_index(op.f("ix_players_sleeper_id"), "players", ["sleeper_id"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("sleeper_user_id", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sleeper_user_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "leagues",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("platform_league_id", sa.String(), nullable=True),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("league_type", sa.String(), nullable=False),
        sa.Column("scoring_format", sa.String(), nullable=False),
        sa.Column("num_teams", sa.Integer(), nullable=False),
        sa.Column("roster_positions", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "platform", "platform_league_id", name="uq_platform_league_id"),
    )
    op.create_index(op.f("ix_leagues_id"), "leagues", ["id"], unique=True)
    op.create_index(op.f("ix_leagues_user_id"), "leagues", ["user_id"], unique=False)
    op.create_table(
        "player_values",
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("league_type", sa.String(), nullable=False),
        sa.Column("scoring_format", sa.String(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("positional_rank", sa.Integer(), nullable=True),
        sa.Column("trend_30day", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_player_value_lookup",
        "player_values",
        ["player_id", "source", "league_type", "scoring_format", "date"],
        unique=True,
    )
    op.create_index(op.f("ix_player_values_id"), "player_values", ["id"], unique=True)
    op.create_index(op.f("ix_player_values_player_id"), "player_values", ["player_id"], unique=False)
    op.create_table(
        "teams",
        sa.Column("league_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("platform_roster_id", sa.String(), nullable=True),
        sa.Column("is_user_team", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["leagues.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_id"), "teams", ["id"], unique=True)
    op.create_index(op.f("ix_teams_league_id"), "teams", ["league_id"], unique=False)
    op.create_index(op.f("ix_teams_user_id"), "teams", ["user_id"], unique=False)
    op.create_table(
        "team_player",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "player_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_player")
    op.drop_index(op.f("ix_teams_user_id"), table_name="teams")
    op.drop_index(op.f("ix_teams_league_id"), table_name="teams")
    op.drop_index(op.f("ix_teams_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_player_values_player_id"), table_name="player_values")
    op.drop_index(op.f("ix_player_values_id"), table_name="player_values")
    op.drop_index("idx_player_value_lookup", table_name="player_values")
    op.drop_table("player_values")
    op.drop_index(op.f("ix_leagues_user_id"), table_name="leagues")
    op.drop_index(op.f("ix_leagues_id"), table_name="leagues")
    op.drop_table("leagues")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_players_sleeper_id"), table_name="players")
    op.drop_index(op.f("ix_players_id"), table_name="players")
    op.drop_index(op.f("ix_players_full_name"), table_name="players")
    op.drop_index(op.f("ix_players_fantasycalc_id"), table_name="players")
    op.drop_table("players")
    # ### end Alembic commands ###
